config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path =>'',
  :path_names=>{:sign_in => 'login',:sign_out => 'logout',:edit => "profile"},
  :controllers => {:registrations => 'registrations',:confirmations => 'confirmations' }
  root 'pages#home'
  resources :users, only: [:show]
  resources :photos
  resources :rooms , path:'annonces' do
    resources :reviews, only: [:create, :destroy]
    resources :reservations, only: [:create]
  end

  get '/preload' => 'reservations#preload'
  get '/preview' => 'reservations#preview'
  get '/your_trips' => 'reservations#your_trips' , path:'mes_voyages'
  get '/search' => 'pages#search'

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

end

app/views/layouts/_navigation.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'MichBnb', root_path, class:"navbar-brand"%>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <%= form_tag search_path, class: "navbar-form navbar-left", method: :get do %>
      <div class="search">
        <span class="fa fa-search"></span>
        <%= text_field_tag :search, params[:search], placeholder: "Rechercher", class: "form-control" %>
      </div>
      <% end %>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to new_room_path do %>
          Devenez hôte
          <% end %>
        </li>
        <li>
          <%= link_to conversations_path do %>
          Messages
          <% end %>
        </li>

        <% unless user_signed_in?%>
        <li><%= link_to "Inscription",new_user_registration_path %></li>
        <li><%= link_to "Connexion",new_user_session_path %></li>
        <% else %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%= image_tag avatar_url(current_user), class:"img-circle avatar-small"%>
            <%=current_user.fullname%>
            <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Mes voyages",your_trips_path %></li>
              <li><%= link_to "Modifier mon profil",edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Déconnexion",destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
          <% end %>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MichBnb</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= favicon_link_tag 'favicon.ico' %>
</head>

<body>
  <%= render 'layouts/navigation' %>
  <div class="container">
    <%= render 'shared/message' %>
    <%= yield %>
  </div>
</body>
</html>